name: Static Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build React app locally
        run: |
          # Run the build command locally or in another environment
          npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure that the build job completes before deployment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: build
          remote: /home/ubuntu/
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}

      - name: Deploy code to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ubuntu/
            sudo rm -rf /var/www/html/
            sudo mv /home/ubuntu/build/* /var/www/html/
            echo "It's Working"
