name: Static Deployment

on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install Node.js and npm
              uses: actions/setup-node@v2
              with:
                node-version: '18'
            
            - name: Install dependencies
              run: npm install
      
            - name: Build React app
              run: npm run build
            - name: Transfer build files to EC2
              env:
                 SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

              run: |
              scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r $GITHUB_WORKSPACE/build ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/


            - name: Deploy code to EC2
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: ${{ secrets.EC2_PORT }}
                script: |
                    cd /home/ubuntu/cloud
                    scp -r build/ ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:
                    sudo rm -rf /var/www/html/*
                    sudo mv build/* /var/www/html/
                    echo "It's Working"